services:
  ecommerce.api:
    image: order-microservice:latest
    build:
      context: .
      dockerfile: eCommerce.API/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_HTTP_PORTS: "8080"
      MONGO_HOST: mongodb
      MONGO_PORT: "27017"
      MONGO_DB: ecommerce-orders-database
    ports:
      - "5000:8080"
    depends_on:
      - mongodb
    networks:
      - ecommerce-network
      - orders-mongo-network

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - ../mongodb-data:/docker-entrypoint-initdb.d
    networks:
      - orders-mongo-network

  users-microservice:
    image: users-microservice:latest
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_HTTP_PORTS: "8080"
      POSTGRES_HOST: postgres
      POSTGRES_PORT: "5432"
      POSTGRES_DB: users-database
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: kbiladze
    ports:
      - "5001:8080"
    depends_on:
      - postgres
    networks:
      - ecommerce-network
      - users-postgres-network

  products-microservice:
    image: products-microservice:latest
    environment:
      ASPNETCORE_HTTP_PORTS: "8080"
      ASPNETCORE_ENVIRONMENT: Development
      MYSQL_HOST: mysql
      MYSQL_PORT: "3306"
      MYSQL_DB: products-database
      MYSQL_USER: products_user
      MYSQL_PASSWORD: kbiladze
    ports:
      - "5002:8080"
    depends_on:
      - mysql
    networks:
      - ecommerce-network
      - products-mysql-network

  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: kbiladze
      MYSQL_DATABASE: products-database
      MYSQL_USER: products_user
      MYSQL_PASSWORD: kbiladze
    ports:
      - "3307:3306"
    volumes:
      - ../mysql-init-scripts:/docker-entrypoint-initdb.d:ro
    networks:
      - products-mysql-network

  postgres:
    image: postgres:latest
    container_name: postgres
    volumes:
      - ../postgres-init-scripts:/docker-entrypoint-initdb.d:ro
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: kbiladze
      POSTGRES_DB: users-database
    ports:
      - "5432:5432"
    networks:
      - users-postgres-network

networks:
  ecommerce-network:
    driver: bridge
  orders-mongo-network:
    driver: bridge
  products-mysql-network:
    driver: bridge
  users-postgres-network:
    driver: bridge